# Generated by Django 6.0.3 on 2026-07-05 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_chatmessage_transcriptline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banned_members',
            field=models.ManyToManyField(blank=True, related_name='banned_from_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
