# Generated by Django 6.0.3 on 2026-07-05 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_banned_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='rooms.chatmessage'),
        ),
        migrations.AddField(
            model_name='transcriptline',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
