# Generated by Django 6.0.3 on 2026-07-05 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('accent_color', models.CharField(choices=[('amber', 'Amber (default)'), ('cyan', 'Cyan'), ('violet', 'Violet'), ('rose', 'Rose'), ('lime', 'Lime'), ('sky', 'Sky')], default='amber', max_length=10)),
                ('mute_mic_on_join', models.BooleanField(default=False)),
                ('notification_sound', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
